apiVersion: v1
kind: Pod
metadata:
  labels:
    app: node-master
    test-network-function.com/generic: fs_diff_master
    test-network-function.com/container: fs_diff_master    
  annotations:
        test-network-function.com/defaultnetworkinterface: '"eth0"' # optional
  name: node-master
  namespace: {{ NAMESPACE_TO_GENERATE }}
spec:
  # hostPID: true
  containers:
    - command:
        - tail
        - -f
        - /dev/null
      image: quay.io/testnetworkfunction/cnf-test-partner:latest # quay.io/testnetworkfunction/test-network-function
      name: master
      resources:
        limits:
          memory: 512Mi
          cpu: 0.25
      volumeMounts:
      - mountPath: /var/lib/containers
        name: var-lib-containers
      - mountPath: /var/run/containers
        name: var-run-containers
      - mountPath: /run/runc
        name: runc-dir
      - mountPath: /var/run/containers/storage/overlay-containers
        name: overlay-containers
      securityContext:
        privileged: true
  restartPolicy: Always
  volumes:
  - name: var-lib-containers
    hostPath:
      path: /var/lib/containers
      type: Directory
  - name: var-run-containers
    hostPath:
      path: /var/run/containers
      type: Directory
  - name: runc-dir
    hostPath:
      path: /run/runc
      type: Directory
  - name: overlay-containers
    hostPath: 
      path: /var/run/containers/storage/overlay-containers
      type: Directory
